spring:
  application:
    name: trace-master-server
  datasource:
    url: jdbc:mysql://localhost:3306/trace_master_server
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root